[package]
name = "file_converter_shell"
version = "0.9.3"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
file_converter_core.workspace = true
scopeguard.workspace = true

[target.'cfg(windows)'.dependencies]
winreg.workspace = true
windows-core.workspace = true
windows.workspace = true
